require('plugins/init-neodev')
require('plugins/init-lsp')
require('plugins/init-tree')
require('plugins/init-treesitter')
require('plugins/init-telescope')
require('plugins/init-statusline')
require('plugins/init-lastplace')
require('plugins/init-smartcolumn')
require('plugins/init-rust-tools')
require('plugins/init-mason')

